insert into productcategory (description) values ('Deposit Slip')

insert into producttype (productcategorykey, description) values (1,'Quick Books')

insert into product (producttypekey, description, price) values (1,'250 Deposit Slips',25)
insert into product (producttypekey, description, price) values (1,'500 Deposit Slips',40)
insert into product (producttypekey, description, price) values (1,'1000 Deposit Slips',70)
insert into product (producttypekey, description, price) values (1,'2000 Deposit Slips',120)
insert into product (producttypekey, description, price) values (1,'3000 Deposit Slips',180)
insert into product (producttypekey, description, price) values (1,'5000 Deposit Slips',300)

insert into addresstype (description) values ('Shipping')
insert into addresstype (description) values ('Billing')

	
insert into state (abbreviation, name) values('AK','Alaska')
insert into state (abbreviation, name) values('AL','Alabama')
insert into state (abbreviation, name) values('AR','Arkansas')
insert into state (abbreviation, name) values('AZ','Arizona')
insert into state (abbreviation, name) values('CA','California')
insert into state (abbreviation, name) values('CO','Colorado')
insert into state (abbreviation, name) values('CT','Connecticut')
insert into state (abbreviation, name) values('DC','District Of Columbia')
insert into state (abbreviation, name) values('DE','Delaware')
insert into state (abbreviation, name) values('FL','Florida')
insert into state (abbreviation, name) values('GA','Georgia')
insert into state (abbreviation, name) values('HI','Hawaii')
insert into state (abbreviation, name) values('IA','Iowa')
insert into state (abbreviation, name) values('ID','Idaho')
insert into state (abbreviation, name) values('IL','Illinois')
insert into state (abbreviation, name) values('IN','Indiana')
insert into state (abbreviation, name) values('KS','Kansas')
insert into state (abbreviation, name) values('KY','Kentucky')
insert into state (abbreviation, name) values('LA','Louisiana')
insert into state (abbreviation, name) values('MA','Massachusetts')
insert into state (abbreviation, name) values('MD','Maryland')
insert into state (abbreviation, name) values('ME','Maine')
insert into state (abbreviation, name) values('MI','Michigan')
insert into state (abbreviation, name) values('MN','Minnesota')
insert into state (abbreviation, name) values('MO','Missouri')
insert into state (abbreviation, name) values('MS','Mississippi')
insert into state (abbreviation, name) values('MT','Montana')
insert into state (abbreviation, name) values('NC','North Carolina')
insert into state (abbreviation, name) values('ND','North Dakota')
insert into state (abbreviation, name) values('NE','Nebraska')
insert into state (abbreviation, name) values('NH','New Hampshire')
insert into state (abbreviation, name) values('NJ','New Jersey')
insert into state (abbreviation, name) values('NM','New Mexico')
insert into state (abbreviation, name) values('NV','Nevada')
insert into state (abbreviation, name) values('NY','New York')
insert into state (abbreviation, name) values('OH','Ohio')
insert into state (abbreviation, name) values('OK','Oklahoma')
insert into state (abbreviation, name) values('OR','Oregon')
insert into state (abbreviation, name) values('PA','Pennsylvania')
insert into state (abbreviation, name) values('RI','Rhode Island')
insert into state (abbreviation, name) values('SC','South Carolina')
insert into state (abbreviation, name) values('SD','South Dakota')
insert into state (abbreviation, name) values('TN','Tennessee')
insert into state (abbreviation, name) values('TX','Texas')
insert into state (abbreviation, name) values('UT','Utah')
insert into state (abbreviation, name) values('VA','Virginia')
insert into state (abbreviation, name) values('VT','Vermont')
insert into state (abbreviation, name) values('WA','Washington')
insert into state (abbreviation, name) values('WI','Wisconsin')
insert into state (abbreviation, name) values('WV','West Virginia')
insert into state (abbreviation, name) values('WY','Wyoming')
